create table if not exists public.location_municipalities (
  id uuid primary key default gen_random_uuid(),
  country_code text not null,
  country_name text not null,
  province_code text not null,
  province_name text not null,
  region_english text not null,
  upper_tier_county_district text not null,
  municipality_type text not null,
  city_municipality text not null,
  created_at timestamptz not null default now(),
  constraint location_municipalities_country_code_check check (char_length(btrim(country_code)) between 2 and 3),
  constraint location_municipalities_country_name_check check (char_length(btrim(country_name)) between 1 and 80),
  constraint location_municipalities_province_code_check check (char_length(btrim(province_code)) between 2 and 20),
  constraint location_municipalities_province_name_check check (char_length(btrim(province_name)) between 1 and 80),
  constraint location_municipalities_region_english_check check (char_length(btrim(region_english)) between 1 and 120),
  constraint location_municipalities_upper_tier_check check (char_length(btrim(upper_tier_county_district)) between 1 and 160),
  constraint location_municipalities_type_check check (char_length(btrim(municipality_type)) between 1 and 80),
  constraint location_municipalities_city_check check (char_length(btrim(city_municipality)) between 1 and 120)
);

comment on table public.location_municipalities
is 'Reference list of municipalities by country, province/state, product region, upper-tier jurisdiction, and municipality type.';

comment on column public.location_municipalities.region_english
is 'Product-facing region or market area label from the Ontario region-city mapping workbook.';

comment on column public.location_municipalities.upper_tier_county_district
is 'Official upper-tier, county, district, or single-tier jurisdiction.';

comment on column public.location_municipalities.city_municipality
is 'City, town, township, municipality, county, or other municipality label from the source mapping.';

create unique index if not exists location_municipalities_unique_idx
  on public.location_municipalities (
    lower(btrim(country_code)),
    lower(btrim(province_code)),
    lower(btrim(region_english)),
    lower(btrim(upper_tier_county_district)),
    lower(btrim(municipality_type)),
    lower(btrim(city_municipality))
  );

create index if not exists idx_location_municipalities_country_province
  on public.location_municipalities (country_code, province_code);

create index if not exists idx_location_municipalities_region
  on public.location_municipalities (province_code, region_english);

alter table public.location_municipalities enable row level security;

drop policy if exists location_municipalities_select_all on public.location_municipalities;
create policy location_municipalities_select_all
  on public.location_municipalities
  for select
  to anon, authenticated
  using (true);

grant select on table public.location_municipalities to anon;
grant select on table public.location_municipalities to authenticated;
grant all on table public.location_municipalities to service_role;

insert into public.location_municipalities (
  country_code,
  country_name,
  province_code,
  province_name,
  region_english,
  upper_tier_county_district,
  municipality_type,
  city_municipality
) values
  ('CA', 'Canada', 'ON', 'Ontario', 'Toronto', 'City of Toronto', 'City', 'Toronto'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'City', 'Markham'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'City', 'Richmond Hill'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'City', 'Vaughan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Town', 'Aurora'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Town', 'East Gwillimbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Town', 'Georgina'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Town', 'Newmarket'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Town', 'Whitchurch-Stouffville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA North / York Region', 'Regional Municipality of York', 'Township', 'King'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Peel Region', 'Regional Municipality of Peel', 'City', 'Brampton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Peel Region', 'Regional Municipality of Peel', 'City', 'Mississauga'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Peel Region', 'Regional Municipality of Peel', 'Town', 'Caledon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Halton Region', 'Regional Municipality of Halton', 'City', 'Burlington'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Halton Region', 'Regional Municipality of Halton', 'Town', 'Halton Hills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Halton Region', 'Regional Municipality of Halton', 'Town', 'Milton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA West / Halton Region', 'Regional Municipality of Halton', 'Town', 'Oakville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Town', 'Ajax'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Township', 'Brock'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Municipality', 'Clarington'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'City', 'Oshawa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'City', 'Pickering'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Township', 'Scugog'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Township', 'Uxbridge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'GTA East / Durham Region', 'Regional Municipality of Durham', 'Town', 'Whitby'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'City of Hamilton', 'City', 'Hamilton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'City', 'Niagara Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'City', 'Port Colborne'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'City', 'St. Catharines'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'City', 'Thorold'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'City', 'Welland'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Town', 'Fort Erie'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Town', 'Grimsby'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Town', 'Lincoln'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Town', 'Niagara-on-the-Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Town', 'Pelham'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Township', 'Wainfleet'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Hamilton & Niagara', 'Regional Municipality of Niagara', 'Township', 'West Lincoln'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'City', 'Cambridge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'City', 'Kitchener'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'City', 'Waterloo'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'Township', 'North Dumfries'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'Township', 'Wellesley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'Township', 'Wilmot'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'Regional Municipality of Waterloo', 'Township', 'Woolwich'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'City', 'Guelph'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Town', 'Erin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Town', 'Minto'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Township', 'Centre Wellington'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Township', 'Guelph/Eramosa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Township', 'Mapleton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Township', 'Puslinch'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Waterloo–Guelph–Wellington', 'County of Wellington', 'Township', 'Wellington North'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Brant–Haldimand–Norfolk', 'County of Brant', 'City', 'Brant'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Brant–Haldimand–Norfolk', 'City of Brantford', 'City', 'Brantford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Brant–Haldimand–Norfolk', 'Haldimand County', 'County', 'Haldimand County'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Brant–Haldimand–Norfolk', 'Norfolk County', 'County', 'Norfolk County'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'City', 'London'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Municipality', 'North Middlesex'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Municipality', 'Southwest Middlesex'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Municipality', 'Thames Centre'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Township', 'Adelaide Metcalfe'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Township', 'Lucan Biddulph'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Township', 'Middlesex Centre'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Municipality', 'Strathroy-Caradoc'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Middlesex', 'Village', 'Newbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'City', 'St. Thomas'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Municipality', 'Bayham'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Municipality', 'Central Elgin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Municipality', 'Dutton/Dunwich'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Municipality', 'West Elgin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Town', 'Aylmer'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Township', 'Malahide'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Elgin', 'Township', 'Southwold'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'City', 'Woodstock'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Town', 'Ingersoll'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Town', 'Tillsonburg'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Township', 'Blandford-Blenheim'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Township', 'East Zorra-Tavistock'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Township', 'Norwich'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Township', 'South-West Oxford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'London & Southwest Ontario', 'County of Oxford', 'Township', 'Zorra'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'City', 'Windsor'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Municipality', 'Leamington'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'Amherstburg'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'Essex'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'Kingsville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'Lakeshore'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'LaSalle'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Town', 'Tecumseh'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'County of Essex', 'Township', 'Pelee'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Windsor–Essex–Chatham', 'Chatham-Kent', 'Municipality', 'Chatham-Kent'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Municipality', 'Arran-Elderslie'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Municipality', 'Brockton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Municipality', 'Kincardine'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Municipality', 'Northern Bruce Peninsula'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Municipality', 'South Bruce'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Town', 'Saugeen Shores'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Town', 'South Bruce Peninsula'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Bruce', 'Township', 'Huron-Kinloss'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'City', 'Owen Sound'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Town', 'The Blue Mountains'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Town', 'Hanover'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Municipality', 'Meaford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Township', 'Chatsworth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Township', 'Georgian Bluffs'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Municipality', 'Grey Highlands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Township', 'Southgate'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Grey', 'Municipality', 'West Grey'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Municipality', 'Bluewater'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Municipality', 'Central Huron'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Municipality', 'Huron East'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Municipality', 'Morris-Turnberry'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Municipality', 'South Huron'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Town', 'Goderich'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Township', 'Ashfield-Colborne-Wawanosh'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Township', 'Howick'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Huron', 'Township', 'North Huron'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'City', 'Stratford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'Municipality', 'North Perth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'Town', 'St. Marys'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'Township', 'Perth East'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'Township', 'Perth South'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Perth', 'Municipality', 'West Perth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'City', 'Sarnia'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Municipality', 'Lambton Shores'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Town', 'Petrolia'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Municipality', 'Brooke-Alvinston'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Township', 'Dawn-Euphemia'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Township', 'Enniskillen'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Town', 'Plympton-Wyoming'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Township', 'St. Clair'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Township', 'Warwick'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Village', 'Oil Springs'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Grey-Bruce, Huron-Perth & Sarnia', 'County of Lambton', 'Village', 'Point Edward'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Town', 'Grand Valley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Town', 'Mono'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Town', 'Orangeville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Town', 'Shelburne'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Township', 'Amaranth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Township', 'East Garafraxa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Township', 'Melancthon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Dufferin', 'Township', 'Mulmur'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'City', 'Barrie'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'City', 'Orillia'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Bradford West Gwillimbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Collingwood'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Innisfil'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Midland'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'New Tecumseth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Penetanguishene'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Town', 'Wasaga Beach'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Adjala-Tosorontio'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Clearview'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Essa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Oro-Medonte'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Ramara'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Severn'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Springwater'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Tay'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'County of Simcoe', 'Township', 'Tiny'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Town', 'Bracebridge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Town', 'Gravenhurst'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Town', 'Huntsville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Township', 'Georgian Bay'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Township', 'Lake of Bays'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'District Municipality of Muskoka', 'Township', 'Muskoka Lakes'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Municipality', 'Callander'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Municipality', 'Magnetawan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Municipality', 'Powassan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Municipality', 'Whitestone'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Town', 'Kearney'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Town', 'Parry Sound'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Armour'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Carling'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Joly'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Machar'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'McDougall'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'McKellar'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'McMurrich/Monteith'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Nipissing'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Perry'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Ryerson'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Seguin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'Strong'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Township', 'The Archipelago'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Village', 'Burk''s Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Village', 'South River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Central Ontario / Barrie–Simcoe–Muskoka', 'Parry Sound District', 'Village', 'Sundridge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'City of Kawartha Lakes', 'City', 'Kawartha Lakes'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Haliburton', 'Township', 'Algonquin Highlands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Haliburton', 'Municipality', 'Dysart et al'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Haliburton', 'Municipality', 'Highlands East'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Haliburton', 'Township', 'Minden Hills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'City', 'Peterborough'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Asphodel-Norwood'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Cavan Monaghan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Douro-Dummer'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Havelock-Belmont-Methuen'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'North Kawartha'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Otonabee-South Monaghan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Township', 'Selwyn'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Peterborough', 'Municipality', 'Trent Lakes'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Municipality', 'Brighton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Town', 'Cobourg'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Municipality', 'Port Hope'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Municipality', 'Trent Hills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Township', 'Alnwick/Haldimand'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Township', 'Cramahe'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kawarthas–Peterborough–Northumberland', 'County of Northumberland', 'Township', 'Hamilton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Frontenac', 'City', 'Kingston'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Frontenac', 'Township', 'Central Frontenac'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Frontenac', 'Township', 'Frontenac Islands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Frontenac', 'Township', 'North Frontenac'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Frontenac', 'Township', 'South Frontenac'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'City', 'Belleville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'City', 'Quinte West'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Municipality', 'Centre Hastings'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Municipality', 'Hastings Highlands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Municipality', 'Marmora and Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Municipality', 'Tweed'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Town', 'Bancroft'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Town', 'Deseronto'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Carlow/Mayo'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Faraday'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Limerick'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Madoc'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Stirling-Rawdon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Tudor and Cashel'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Tyendinaga'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Hastings', 'Township', 'Wollaston'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Lennox and Addington', 'Town', 'Greater Napanee'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Lennox and Addington', 'Township', 'Addington Highlands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Lennox and Addington', 'Township', 'Loyalist'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'County of Lennox and Addington', 'Township', 'Stone Mills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Kingston & Quinte', 'Prince Edward County', 'County', 'Prince Edward County'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'City of Ottawa', 'City', 'Ottawa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Town', 'Smiths Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Municipality', 'Mississippi Mills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Town', 'Carleton Place'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Town', 'Perth'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Township', 'Beckwith'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Township', 'Drummond/North Elmsley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Township', 'Lanark Highlands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Township', 'Montague'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Lanark', 'Township', 'Tay Valley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'City', 'Brockville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Municipality', 'North Grenville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Town', 'Gananoque'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Town', 'Prescott'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Athens'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Augusta'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Edwardsburgh/Cardinal'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Elizabethtown-Kitley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Leeds and the Thousand Islands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Front of Yonge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Township', 'Rideau Lakes'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Village', 'Merrickville-Wolford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Leeds and Grenville', 'Village', 'Westport'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'City', 'Pembroke'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Town', 'Arnprior'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Town', 'Deep River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Town', 'Laurentian Hills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Town', 'Petawawa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Town', 'Renfrew'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Admaston/Bromley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Bonnechere Valley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Brudenell, Lyndoch and Raglan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Greater Madawaska'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Horton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Killaloe, Hagarty and Richards'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Laurentian Valley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Madawaska Valley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'McNab/Braeside'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'North Algona Wilberforce'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Whitewater'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'County of Renfrew', 'Township', 'Head, Clara and Maria'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'City', 'Clarence-Rockland'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Municipality', 'Casselman'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Municipality', 'The Nation'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Town', 'Hawkesbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Township', 'Alfred and Plantagenet'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Township', 'Champlain'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Township', 'East Hawkesbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Prescott and Russell', 'Township', 'Russell'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'City', 'Cornwall'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Municipality', 'South Dundas'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Township', 'North Dundas'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Township', 'North Glengarry'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Township', 'North Stormont'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Township', 'South Glengarry'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Ottawa & Eastern Ontario', 'United Counties of Stormont, Dundas and Glengarry', 'Township', 'South Stormont'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'City of Greater Sudbury', 'City', 'Greater Sudbury'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'City', 'Elliot Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'City', 'Sault Ste. Marie'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Municipality', 'Huron Shores'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Town', 'Blind River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Town', 'Bruce Mines'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Town', 'Thessalon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Dubreuilville'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Hilton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Hornepayne'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Jocelyn'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Johnson'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Laird'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Macdonald, Meredith & Aberdeen Add''l'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Municipality', 'Wawa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Plummer Additional'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Prince'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Spanish'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'St. Joseph'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'Tarbutt'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'The North Shore'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Township', 'White River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Algoma District', 'Village', 'Hilton Beach'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'City', 'Timmins'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Cochrane'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Hearst'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Iroquois Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Kapuskasing'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Moosonee'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Town', 'Smooth Rock Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Black River-Matheson'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Fauquier-Strickland'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Mattice-Val Côté'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Moonbeam'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Opasatika'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Cochrane District', 'Township', 'Val Rita-Harty'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Town', 'Gore Bay'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Town', 'Northeastern Manitoulin and the Islands'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Township', 'Assiginack'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Municipality', 'Billings'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Township', 'Burpee and Mills'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Municipality', 'Central Manitoulin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Township', 'Cockburn Island'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Municipality', 'Gordon/Barrie Island'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Manitoulin District', 'Township', 'Tehkummah'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'City', 'North Bay'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Municipality', 'Temagami'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Municipality', 'West Nipissing'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Town', 'Mattawa'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'Bonfield'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'Calvin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'Chisholm'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Municipality', 'East Ferris'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'Mattawan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'Papineau-Cameron'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Nipissing District', 'Township', 'South Algonquin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Municipality', 'French River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Municipality', 'Killarney'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Municipality', 'Markstay-Warren'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Municipality', 'St. Charles'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Town', 'Espanola'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Township', 'Baldwin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Township', 'Chapleau'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Township', 'Nairn and Hyman'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Sudbury District', 'Township', 'Sables-Spanish Rivers'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'City', 'Temiskaming Shores'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Municipality', 'Charlton and Dack'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Town', 'Cobalt'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Town', 'Englehart'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Town', 'Kirkland Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Town', 'Latchford'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Armstrong'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Brethour'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Casey'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Chamberlain'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Coleman'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Evanturel'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Gauthier'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Harley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Harris'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Hilliard'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Hudson'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'James'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Kerns'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Larder Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'Matachewan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Township', 'McGarry'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northeastern Ontario', 'Timiskaming District', 'Village', 'Thornloe'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'City', 'Dryden'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'City', 'Kenora'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Municipality', 'Red Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Municipality', 'Sioux Lookout'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Township', 'Ear Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Township', 'Ignace'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Township', 'Machin'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Township', 'Pickle Lake'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Kenora District', 'Township', 'Sioux Narrows-Nestor Falls'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Town', 'Fort Frances'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Town', 'Rainy River'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Alberton'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Atikokan'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Chapple'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Dawson'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Emo'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'La Vallee'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Lake of the Woods'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Rainy River District', 'Township', 'Morley'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'City', 'Thunder Bay'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Municipality', 'Greenstone'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Municipality', 'Neebing'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Municipality', 'Oliver Paipoonge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Town', 'Marathon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Conmee'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Dorion'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Gillies'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Manitouwadge'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Nipigon'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'O''Connor'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Red Rock'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Schreiber'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Municipality', 'Shuniah'),
  ('CA', 'Canada', 'ON', 'Ontario', 'Northwestern Ontario', 'Thunder Bay District', 'Township', 'Terrace Bay')
on conflict do nothing;
